"""init db

Revision ID: 27ff8d6f3e21
Revises: 
Create Date: 2017-02-19 18:02:36.516871

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '27ff8d6f3e21'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Table_Test',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('firstname', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Table_Test_firstname'), 'Table_Test', ['firstname'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_Table_Test_firstname'), table_name='Table_Test')
    op.drop_table('Table_Test')
    # ### end Alembic commands ###
